/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Car_Details;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author vrushankhiremath
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Car_Details car;
    
    public String name_error = "";
    public String error = "";
    
    public CreateJPanel(Car_Details car) {
        initComponents();
        this.car=car;
    }

   private void Owner_Name_Validation(){
       if(txtOwnerName.getText().isEmpty()){
           name_error = "Owner Name";
       }
       else{
           name_error = "";
       }
   }
   
   private void Seat_Number_Validation(){
       try 
        {
            Integer.parseInt(txtSeatNumber.getText());
            error = "";
        } 
        catch (NumberFormatException e) 
        {
            error = "Enter Number Only";
        }
          
   }
   
   private void Telephone_Number_Validation(){
       try 
        {
            Integer.parseInt(txtOwnerTelephoneNumber.getText());
            if (txtOwnerTelephoneNumber.getText().length()<10 || txtOwnerTelephoneNumber.getText().length()<10){
                error = "Enter Correct Number";
                
            }
            else{
                error = "";
            }
            error = "";
        } 
        catch (NumberFormatException e) 
        {
            error = "Enter Number Only";
        }
       
   }
   
   private void Owner_Email_Validation(){
       
       
       try 
        {
            Integer.parseInt(txtOwnerEmailAddress.getText());
            error = "Incorrect Email Address";
        } 
        catch (NumberFormatException e) 
        {
           error = "";
        }
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel = new javax.swing.JPanel();
        lblCreateCarProfile = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblEngineNo = new javax.swing.JLabel();
        lblSeatsNumber = new javax.swing.JLabel();
        lblLicensePlates = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        lblOwnerTelephoneNumber = new javax.swing.JLabel();
        lblOwnerEmailAddress = new javax.swing.JLabel();
        lblOwnerDriverLicense = new javax.swing.JLabel();
        lblOwnerSocialSecurityNumber = new javax.swing.JLabel();
        lblOwnerAddress = new javax.swing.JLabel();
        lblServiceRecords = new javax.swing.JLabel();
        lblWarrantyYear = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtEngineNo = new javax.swing.JTextField();
        txtSeatNumber = new javax.swing.JTextField();
        txtLicensePlates = new javax.swing.JTextField();
        txtOwnerName = new javax.swing.JTextField();
        txtOwnerEmailAddress = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtOwnerDriverLicense = new javax.swing.JTextField();
        txtOwnerTelephoneNumber = new javax.swing.JTextField();
        txtOwnerAddress = new javax.swing.JTextField();
        txtOwnerSocialSecurityNumber = new javax.swing.JTextField();
        txtWarrantyYear = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        lblnameerr = new javax.swing.JLabel();
        lblemailerr = new javax.swing.JLabel();
        lblnumerr = new javax.swing.JLabel();
        lblssnerr = new javax.swing.JLabel();
        lblyearerr = new javax.swing.JLabel();
        txtServiceRecords = new javax.swing.JTextField();

        lblCreateCarProfile.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCreateCarProfile.setText("Create Car Profile");
        lblCreateCarProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblBrand.setText("Brand:");

        lblModel.setText("Model:");

        lblColor.setText("Color:");

        lblYear.setText("Year:");

        lblEngineNo.setText("Engine No:");

        lblSeatsNumber.setText("Seats Number:");

        lblLicensePlates.setText("License Plates:");

        lblOwnerName.setText("Owner Name:");

        lblOwnerTelephoneNumber.setText("Owner Telephone Number:");

        lblOwnerEmailAddress.setText("Owner Email Address:");

        lblOwnerDriverLicense.setText("Owner Driver License:");

        lblOwnerSocialSecurityNumber.setText("Owner Social Security Number:");

        lblOwnerAddress.setText("Owner Address:");

        lblServiceRecords.setText("Service Records:");

        lblWarrantyYear.setText("Warranty Year:");

        lblPhoto.setText("Photo:");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModelKeyPressed(evt);
            }
        });

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        txtBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrandKeyPressed(evt);
            }
        });

        txtEngineNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEngineNoActionPerformed(evt);
            }
        });
        txtEngineNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEngineNoKeyPressed(evt);
            }
        });

        txtSeatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatNumberActionPerformed(evt);
            }
        });
        txtSeatNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeatNumberKeyPressed(evt);
            }
        });

        txtLicensePlates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicensePlatesActionPerformed(evt);
            }
        });
        txtLicensePlates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLicensePlatesKeyPressed(evt);
            }
        });

        txtOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerNameActionPerformed(evt);
            }
        });
        txtOwnerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOwnerNameKeyPressed(evt);
            }
        });

        txtOwnerEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerEmailAddressActionPerformed(evt);
            }
        });
        txtOwnerEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOwnerEmailAddressKeyPressed(evt);
            }
        });

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
        });

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtColorKeyPressed(evt);
            }
        });

        txtOwnerDriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerDriverLicenseActionPerformed(evt);
            }
        });
        txtOwnerDriverLicense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOwnerDriverLicenseKeyPressed(evt);
            }
        });

        txtOwnerTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerTelephoneNumberActionPerformed(evt);
            }
        });
        txtOwnerTelephoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOwnerTelephoneNumberKeyPressed(evt);
            }
        });

        txtOwnerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerAddressActionPerformed(evt);
            }
        });
        txtOwnerAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOwnerAddressKeyPressed(evt);
            }
        });

        txtOwnerSocialSecurityNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerSocialSecurityNumberActionPerformed(evt);
            }
        });
        txtOwnerSocialSecurityNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOwnerSocialSecurityNumberKeyPressed(evt);
            }
        });

        txtWarrantyYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWarrantyYearActionPerformed(evt);
            }
        });
        txtWarrantyYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWarrantyYearKeyPressed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtServiceRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOwnerTelephoneNumber)
                    .addComponent(lblOwnerEmailAddress)
                    .addComponent(lblOwnerDriverLicense)
                    .addComponent(lblOwnerSocialSecurityNumber)
                    .addComponent(lblPhoto)
                    .addComponent(lblOwnerName)
                    .addComponent(lblLicensePlates)
                    .addComponent(lblSeatsNumber)
                    .addComponent(lblEngineNo)
                    .addComponent(lblYear)
                    .addComponent(lblColor)
                    .addComponent(lblModel)
                    .addComponent(lblBrand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(txtOwnerEmailAddress)
                    .addComponent(txtModel)
                    .addComponent(txtEngineNo)
                    .addComponent(txtBrand)
                    .addComponent(txtSeatNumber)
                    .addComponent(txtLicensePlates)
                    .addComponent(txtOwnerName)
                    .addComponent(txtYear)
                    .addComponent(txtColor)
                    .addComponent(txtOwnerTelephoneNumber)
                    .addComponent(txtOwnerSocialSecurityNumber))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblssnerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(455, 455, 455))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblemailerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addComponent(lblnumerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addComponent(lblnameerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(458, 458, 458))))))
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblCreateCarProfile))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOwnerAddress)
                            .addComponent(lblServiceRecords)
                            .addComponent(lblWarrantyYear))
                        .addGap(97, 97, 97)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(lblyearerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(btnSave))
                                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtServiceRecords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                        .addComponent(txtOwnerAddress, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 12, Short.MAX_VALUE)))))
                .addGap(444, 444, 444))
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCreateCarProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel))
                        .addGap(13, 13, 13)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYear))
                        .addGap(12, 12, 12)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEngineNo))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeatsNumber))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicensePlates)))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOwnerName))
                        .addGap(23, 23, 23)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerTelephoneNumber)
                                    .addComponent(lblnumerr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerEmailAddress)
                                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblemailerr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerDriverLicense)
                                    .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtOwnerTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblnameerr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblssnerr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtOwnerSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblOwnerSocialSecurityNumber))
                .addGap(28, 28, 28)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerAddress)
                    .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceRecords)
                    .addComponent(txtServiceRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblPhoto))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWarrantyYear))
                            .addComponent(lblyearerr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpload)
                            .addComponent(btnSave))))
                .addGap(362, 362, 362))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyPressed
        // TODO add your handling code here:

        //code to accept only Alphabets

        // TO DO add your handling code here:

        
    }//GEN-LAST:event_txtModelKeyPressed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandKeyPressed

    private void txtEngineNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEngineNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEngineNoActionPerformed

    private void txtEngineNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEngineNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEngineNoKeyPressed

    private void txtSeatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSeatNumberActionPerformed

    private void txtSeatNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatNumberKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtSeatNumberKeyPressed

    private void txtLicensePlatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicensePlatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicensePlatesActionPerformed

    private void txtLicensePlatesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicensePlatesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicensePlatesKeyPressed

    private void txtOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerNameActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtOwnerNameActionPerformed

    private void txtOwnerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOwnerNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            txtOwnerName.setEditable(false);
            lblnameerr.setText("Please enter letters only!");
        }
        else
        {
            txtOwnerName.setEditable(true);
            lblnameerr.setText(""); // To disable the warnings once user feed correct character
        }
    }//GEN-LAST:event_txtOwnerNameKeyPressed

    private void txtOwnerEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerEmailAddressActionPerformed

    private void txtOwnerEmailAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOwnerEmailAddressKeyPressed
        // TODO add your handling code here:
        String emailAddress = "^[\\w-\\.+]*[\\w-\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
         if (!txtOwnerEmailAddress.getText().isEmpty() && !txtOwnerEmailAddress.getText().matches(emailAddress)){
                //isInValid = true;       
                lblemailerr.setText("Please enter correct Email ID") ; 
                
                    }
         else{
             lblemailerr.setText(" ") ; 
             
         }
    }//GEN-LAST:event_txtOwnerEmailAddressKeyPressed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearKeyPressed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorKeyPressed

    private void txtOwnerDriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerDriverLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerDriverLicenseActionPerformed

    private void txtOwnerDriverLicenseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOwnerDriverLicenseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerDriverLicenseKeyPressed

    private void txtOwnerTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerTelephoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerTelephoneNumberActionPerformed

    private void txtOwnerTelephoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOwnerTelephoneNumberKeyPressed
        // TODO add your handling code here:
        String Telephonenumber = txtOwnerTelephoneNumber.getText();
        //get length of a string
        int length =Telephonenumber.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                //editable true
                txtOwnerTelephoneNumber.setEditable(true);
                lblnumerr.setText("Please enter Phone No only!");
            }else{
                //not editable for length more than 10 digits 
                txtOwnerTelephoneNumber.setEditable(false);
                lblnumerr.setText(" ");
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtOwnerTelephoneNumber.setEditable(true);
                
            }else{
                txtOwnerTelephoneNumber.setEditable(false);
            }
                
            
            
        }
           
    }//GEN-LAST:event_txtOwnerTelephoneNumberKeyPressed

    private void txtOwnerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerAddressActionPerformed

    private void txtOwnerAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOwnerAddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerAddressKeyPressed

    private void txtOwnerSocialSecurityNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerSocialSecurityNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerSocialSecurityNumberActionPerformed

    private void txtOwnerSocialSecurityNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOwnerSocialSecurityNumberKeyPressed
        // TODO add your handling code here:
         String SSN=txtOwnerSocialSecurityNumber.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='8'){
            if (length<10){
                //editable true
                txtOwnerSocialSecurityNumber.setEditable(true);
                lblssnerr.setText("Please enter SSN Number only!");
            }else{
                //not editable for length more than 10 digits 
                txtOwnerSocialSecurityNumber.setEditable(false);
                lblssnerr.setText("");
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtOwnerSocialSecurityNumber.setEditable(true);
                
            }else{
                txtOwnerSocialSecurityNumber.setEditable(false);
            }
                
            
           }
    }//GEN-LAST:event_txtOwnerSocialSecurityNumberKeyPressed

    private void txtWarrantyYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarrantyYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarrantyYearActionPerformed

    private void txtWarrantyYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWarrantyYearKeyPressed
        // TODO add your handling code here:
         String Telephonenumber = txtWarrantyYear.getText();
        //get length of a string
        int length =Telephonenumber.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<4){
                //editable true
                txtWarrantyYear.setEditable(true);
                lblyearerr.setText("Please enter year No only!");
            }else{
                //not editable for length more than 10 digits 
                txtWarrantyYear.setEditable(false);
                lblyearerr.setText(" ");
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtWarrantyYear.setEditable(true);
                
            }else{
                txtWarrantyYear.setEditable(false);
            }
                
            
            
        }
    }//GEN-LAST:event_txtWarrantyYearKeyPressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
                  car.setBrand(txtBrand.getText());
                  car.setColor(txtColor.getText());
                  car.setEngine_No(txtEngineNo.getText());
                  car.setLicense_plates(txtLicensePlates.getText());
                  car.setModel(txtModel.getText());
                  car.setOwner_address(txtOwnerAddress.getText());
                  car.setOwner_Driver_license(txtOwnerDriverLicense.getText());
                  car.setOwner_Email_address(txtOwnerEmailAddress.getText());
                  car.setOwner_Name(txtOwnerName.getText());
                  car.setOwner_Social_Security_number(txtOwnerSocialSecurityNumber.getText());
                  car.setOwner_Telephone_number(txtOwnerTelephoneNumber.getText());
                  car.setSeat_Number(txtSeatNumber.getText());
                  car.setService_records(txtServiceRecords.getText());
                  car.setWarranty_Year(txtWarrantyYear.getText());
                  car.setYear(txtYear.getText());
                  
                  
                  JOptionPane.showMessageDialog(this, "Car profile data saved successfully");
                  

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
       JFileChooser chooser = new JFileChooser();
       FileNameExtensionFilter extensionvali = new FileNameExtensionFilter("4 Extensions Supported","jpg","png","jpeg","gif");
       chooser.setFileFilter(extensionvali);
       int selected = chooser.showOpenDialog(null);
       if (selected == JFileChooser.APPROVE_OPTION){
           File file = chooser.getSelectedFile();
           String getimage = file.getAbsolutePath();
           //JOptionPane.showMessageDialog(null, image);
           ImageIcon icon = new ImageIcon(getimage);
           Image iconfit = icon.getImage();
           Image imgfit = iconfit.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
           
           image.setIcon(icon);
           car.setPhoto(getimage);
           
       }
       
       
       
       
       
        
        
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtServiceRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceRecordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceRecordsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel image;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCreateCarProfile;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblLicensePlates;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerDriverLicense;
    private javax.swing.JLabel lblOwnerEmailAddress;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSocialSecurityNumber;
    private javax.swing.JLabel lblOwnerTelephoneNumber;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSeatsNumber;
    private javax.swing.JLabel lblServiceRecords;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblemailerr;
    private javax.swing.JLabel lblnameerr;
    private javax.swing.JLabel lblnumerr;
    private javax.swing.JLabel lblssnerr;
    private javax.swing.JLabel lblyearerr;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlates;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerAddress;
    private javax.swing.JTextField txtOwnerDriverLicense;
    private javax.swing.JTextField txtOwnerEmailAddress;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtOwnerSocialSecurityNumber;
    private javax.swing.JTextField txtOwnerTelephoneNumber;
    private javax.swing.JTextField txtSeatNumber;
    private javax.swing.JTextField txtServiceRecords;
    private javax.swing.JTextField txtWarrantyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    
}
